name: Ruby CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: bundle exec rspec
